import {Audio, Video} from '@remotion/media';
import {AbsoluteFill, Img, Sequence, interpolate, staticFile, useCurrentFrame} from 'remotion';

const FPS=30;
export const TOMCAT_FUSION_DURATION=2160;
const cyan='#59E7FF', pink='#FF5B9D', orange='#FF8A3D', lime='#DDF56B', ink='#05090F', white='#F4F7F8', muted='#93A5B0';
const clamp={extrapolateLeft:'clamp',extrapolateRight:'clamp'} as const;
type Mode='temperature'|'density'|'magnet'|'paths'|'engineering'|'record'|'end';

const Brand=()=> <div style={{position:'absolute',top:34,left:42,right:42,display:'flex',justifyContent:'space-between',alignItems:'center',zIndex:20}}>
  <div style={{fontSize:28,fontWeight:950,letterSpacing:-1}}>大厂汤姆猫</div><div style={{fontFamily:'Bahnschrift, sans-serif',fontSize:16,letterSpacing:2,color:cyan}}>SCIENCE / 01</div>
</div>;

const Chamber:React.FC<{mode:Mode}>=({mode})=>{const f=useCurrentFrame();const pulse=interpolate(Math.sin(f/10),[-1,1],[.96,1.04]);return <div style={{position:'absolute',left:56,right:56,top:215,height:610}}>
  <div style={{position:'absolute',left:42,top:35,width:520,height:520,borderRadius:'50%',border:'34px solid #263844',boxShadow:'inset 0 0 55px #000,0 0 0 2px #557080'}}/>
  <div style={{position:'absolute',left:122,top:115,width:360,height:360,borderRadius:'50%',border:`58px solid ${pink}`,boxShadow:`0 0 38px ${pink}`,opacity:.88,scale:pulse}}/>
  <div style={{position:'absolute',left:240,top:235,width:120,height:120,borderRadius:'50%',background:ink}}/>
  {mode==='density'&&Array.from({length:18},(_,i)=><div key={i} style={{position:'absolute',left:165+(i*67)%290,top:165+(i*43)%265,width:7,height:7,borderRadius:'50%',background:i%3?cyan:lime,boxShadow:`0 0 10px ${cyan}`,opacity:interpolate(f,[0,14],[0,1],clamp)}}/>)}
  {mode==='magnet'&&[0,1,2].map(i=><div key={i} style={{position:'absolute',left:98-i*13,top:91-i*13,width:410+i*26,height:410+i*26,borderRadius:'50%',border:`3px solid ${cyan}`,opacity:.35+i*.18,rotate:`${f*.18+i*17}deg`}}/>)}
  {mode==='paths'&&<><div style={{position:'absolute',left:298,top:480,width:6,height:120,background:orange,rotate:'18deg',transformOrigin:'top',boxShadow:`0 0 12px ${orange}`}}/><div style={{position:'absolute',left:70,top:170,width:500,height:3,background:`linear-gradient(90deg,transparent,${pink},transparent)`,rotate:'-18deg'}}/><div style={{position:'absolute',left:85,top:390,width:510,height:3,background:`linear-gradient(90deg,transparent,${lime},transparent)`,rotate:'24deg'}}/></>}
  {mode==='engineering'&&<><div style={{position:'absolute',left:245,top:500,width:110,height:55,background:orange,clipPath:'polygon(0 0,100% 0,78% 100%,22% 100%)',boxShadow:`0 0 18px ${orange}`}}/><div style={{position:'absolute',left:263,top:526,width:76,height:11,background:cyan}}/></>}
  {mode==='record'&&<div style={{position:'absolute',left:43,top:35,width:520,height:520,borderRadius:'50%',background:'#05090FBB',display:'grid',placeItems:'center'}}><div style={{fontFamily:'Bahnschrift',fontSize:96,fontWeight:900,color:lime}}>1066<span style={{fontSize:35}}> s</span></div></div>}
</div>};

const Caption:React.FC<{text:string;source?:string}>=({text,source})=><div style={{position:'absolute',left:38,right:38,bottom:60,zIndex:20}}><div style={{borderTop:`3px solid ${cyan}`,background:'#071119EE',padding:'22px 24px 20px',fontSize:34,lineHeight:1.35,fontWeight:850}}>{text}</div>{source&&<div style={{fontSize:17,color:muted,marginTop:10}}>{source}</div>}</div>;
const Label:React.FC<{children:React.ReactNode;color?:string}>=({children,color=cyan})=><div style={{position:'absolute',left:54,top:145,fontSize:54,fontWeight:950,lineHeight:1.1,color}}>{children}</div>;

const Opening=()=> <AbsoluteFill><Video src={staticFile('tomcat-01/tokamak-opener.mp4')} muted objectFit="cover" style={{width:'100%',height:'100%'}}/><div style={{position:'absolute',inset:0,background:'linear-gradient(180deg,#0007,transparent 45%,#000A)'}}/><Brand/><div style={{position:'absolute',left:42,top:805,fontSize:76,lineHeight:1.03,fontWeight:950}}>一亿度<br/><span style={{color:lime}}>机器为什么没烧穿？</span></div><div style={{position:'absolute',right:38,bottom:35,fontSize:16,color:muted}}>科学示意 · 非真实装置</div></AbsoluteFill>;
const Temp=()=> <><Brand/><Label>核心温度<br/><span style={{color:lime}}>≠ 壁面温度</span></Label><Chamber mode="temperature"/><Caption text="关键不是哪块金属能硬扛一亿度" source="原理依据：Max Planck IPP · 核心与壁温需区分"/></>;
const Density=()=> <><Brand/><Label>高温，也很<span style={{color:lime}}>稀薄</span></Label><Chamber mode="density"/><div style={{position:'absolute',left:70,top:830,right:70,fontSize:26,color:muted}}>稀薄能减少传热，但壁面热负荷依然巨大</div><Caption text="温度反映粒子运动有多剧烈"/></>;
const Magnet=()=> <><Brand/><Label>第一道防线<br/><span style={{color:cyan}}>磁约束</span></Label><Chamber mode="magnet"/><Caption text="让带电粒子绕着磁力线，核心尽量不直接碰壁" source="ITER：托卡马克以强磁场约束等离子体"/></>;
const Paths=()=> <><Brand/><Label>磁场不是<span style={{color:orange}}>绝热罩</span></Label><Chamber mode="paths"/><div style={{position:'absolute',top:800,left:55,right:55,display:'flex',gap:12,fontSize:20}}><div style={{flex:1,color:orange}}>边缘带电粒子<br/>→ 偏滤器</div><div style={{flex:1,color:pink}}>辐射<br/>→ 广泛壁面</div><div style={{flex:1,color:lime}}>未来 DT 中子<br/>→ 包层</div></div><Caption text="不同能量，必须送到不同部件" source="未来氘氚工况示意；不代表 EAST 已商业发电"/></>;
const Engineering=()=>{const f=useCurrentFrame();return <><Brand/><Label>真正的硬仗<br/><span style={{color:orange}}>把热带走</span></Label><Chamber mode="engineering"/><div style={{position:'absolute',right:48,top:650,width:245,height:160,overflow:'hidden',border:'2px solid #88A5B5'}}><Img src={staticFile('tomcat-01/references/west-vacuum-chamber.jpg')} style={{width:'150%',height:'100%',objectFit:'cover',translate:`${interpolate(f,[0,428],[0,-90],clamp)}px 0`}}/></div><div style={{position:'absolute',right:52,top:785,fontSize:14,background:'#05090FDD',padding:6}}>WEST 装置内壁资料照片</div><div style={{position:'absolute',left:58,top:840,fontFamily:'Bahnschrift',fontSize:75,fontWeight:900,color:lime}}>10 MW/m²</div><div style={{position:'absolute',left:60,top:920,fontSize:20,color:muted}}>ITER 偏滤器稳态设计热流</div><Caption text="偏滤器排集中热流；包层和真空室承担另一部分负荷" source="WEST photo: Christophe Roux / IRFM, CC BY 4.0 · cropped/annotated"/></>};
const Record=()=> <><Brand/><Label>难点是<span style={{color:lime}}>稳定多久</span></Label><Chamber mode="record"/><div style={{position:'absolute',left:58,top:825,right:58,display:'flex',justifyContent:'space-between',fontSize:23}}><span>2025-01-20</span><span style={{color:muted}}>EAST · 历史研究纪录</span></div><Caption text="稳态高约束模运行 1066 秒，不等于已经商业发电" source="中国科学院，2025-01-21"/></>;
const End=()=> <><Brand/><Label>不是机器不怕热</Label><Chamber mode="end"/><div style={{position:'absolute',left:62,right:62,top:805,display:'flex',flexDirection:'column',gap:16,fontSize:34,fontWeight:900}}><div><span style={{color:cyan}}>01</span> 磁约束</div><div><span style={{color:orange}}>02</span> 材料承载</div><div><span style={{color:lime}}>03</span> 主动排热</div></div><Caption text="三者一起，争取稳定运行的时间"/></>;

const scenes=[{from:0,to:90,view:Opening},{from:90,to:316,view:Temp},{from:316,to:559,view:Density},{from:559,to:895,view:Magnet},{from:895,to:1247,view:Paths},{from:1247,to:1675,view:Engineering},{from:1675,to:1953,view:Record},{from:1953,to:2160,view:End}];
export const TomcatFusion:React.FC=()=> <AbsoluteFill style={{background:ink,color:white,fontFamily:'Noto Sans SC, Microsoft YaHei, sans-serif',overflow:'hidden'}}><div style={{position:'absolute',inset:0,backgroundImage:'linear-gradient(#17314255 1px,transparent 1px),linear-gradient(90deg,#17314255 1px,transparent 1px)',backgroundSize:'42px 42px',opacity:.22}}/>{scenes.map((s,i)=><Sequence key={i} from={s.from} durationInFrames={s.to-s.from}><s.view/></Sequence>)}<Audio src={staticFile('tomcat-01/audio/narration.mp3')}/><Audio src={staticFile('tomcat-01/audio/bgm.wav')} loop volume={(f)=>interpolate(f,[0,FPS,2070,2160],[0,.105,.105,0],clamp)}/></AbsoluteFill>;

export const TomcatFusionCover:React.FC=()=> <AbsoluteFill style={{background:ink,color:white,fontFamily:'Noto Sans SC, Microsoft YaHei, sans-serif',padding:48}}><div style={{position:'absolute',inset:22,border:`2px solid ${cyan}`}}/><div style={{fontSize:30,fontWeight:950}}>大厂汤姆猫</div><div style={{marginTop:180,fontSize:110,fontWeight:950,lineHeight:.98}}>一亿度<br/><span style={{color:lime}}>怎么没烧穿？</span></div><div style={{marginTop:55,fontSize:30,color:muted}}>磁约束不是绝热罩，热究竟去了哪</div><div style={{position:'absolute',left:48,right:48,bottom:76,height:10,background:`linear-gradient(90deg,${cyan},${pink},${orange})`}}/></AbsoluteFill>;

